/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OpenFinanceRouteImport } from './routes/open-finance'
import { Route as InstallmentsRouteImport } from './routes/installments'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditCardsRouteImport } from './routes/credit-cards'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TransactionsNewRouteImport } from './routes/transactions.new'
import { Route as TransactionsEditIdRouteImport } from './routes/transactions.edit.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenFinanceRoute = OpenFinanceRouteImport.update({
  id: '/open-finance',
  path: '/open-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsRoute = InstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRoute = CreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsEditIdRoute = TransactionsEditIdRouteImport.update({
  id: '/transactions/edit/$id',
  path: '/transactions/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/open-finance': typeof OpenFinanceRoute
  '/settings': typeof SettingsRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/open-finance': typeof OpenFinanceRoute
  '/settings': typeof SettingsRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/import': typeof ImportRoute
  '/installments': typeof InstallmentsRoute
  '/open-finance': typeof OpenFinanceRoute
  '/settings': typeof SettingsRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/chat'
    | '/credit-cards'
    | '/dashboard'
    | '/forecast'
    | '/import'
    | '/installments'
    | '/open-finance'
    | '/settings'
    | '/transactions/new'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/chat'
    | '/credit-cards'
    | '/dashboard'
    | '/forecast'
    | '/import'
    | '/installments'
    | '/open-finance'
    | '/settings'
    | '/transactions/new'
    | '/transactions'
    | '/transactions/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/chat'
    | '/credit-cards'
    | '/dashboard'
    | '/forecast'
    | '/import'
    | '/installments'
    | '/open-finance'
    | '/settings'
    | '/transactions/new'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  CategoriesRoute: typeof CategoriesRoute
  ChatRoute: typeof ChatRoute
  CreditCardsRoute: typeof CreditCardsRoute
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  ImportRoute: typeof ImportRoute
  InstallmentsRoute: typeof InstallmentsRoute
  OpenFinanceRoute: typeof OpenFinanceRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TransactionsEditIdRoute: typeof TransactionsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-finance': {
      id: '/open-finance'
      path: '/open-finance'
      fullPath: '/open-finance'
      preLoaderRoute: typeof OpenFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments': {
      id: '/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof InstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/edit/$id': {
      id: '/transactions/edit/$id'
      path: '/transactions/edit/$id'
      fullPath: '/transactions/edit/$id'
      preLoaderRoute: typeof TransactionsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  CategoriesRoute: CategoriesRoute,
  ChatRoute: ChatRoute,
  CreditCardsRoute: CreditCardsRoute,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  ImportRoute: ImportRoute,
  InstallmentsRoute: InstallmentsRoute,
  OpenFinanceRoute: OpenFinanceRoute,
  SettingsRoute: SettingsRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TransactionsEditIdRoute: TransactionsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
