/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOpenFinanceRouteImport } from './routes/_app.open-finance'
import { Route as AppInstallmentsRouteImport } from './routes/_app.installments'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppForecastRouteImport } from './routes/_app.forecast'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreditCardsRouteImport } from './routes/_app.credit-cards'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppBudgetsRouteImport } from './routes/_app.budgets'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app.transactions.index'
import { Route as AppTransactionsNewRouteImport } from './routes/_app.transactions.new'
import { Route as AppTransactionsEditIdRouteImport } from './routes/_app.transactions.edit.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOpenFinanceRoute = AppOpenFinanceRouteImport.update({
  id: '/open-finance',
  path: '/open-finance',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallmentsRoute = AppInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditCardsRoute = AppCreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsNewRoute = AppTransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsEditIdRoute = AppTransactionsEditIdRouteImport.update({
  id: '/transactions/edit/$id',
  path: '/transactions/edit/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/chat': typeof AppChatRoute
  '/credit-cards': typeof AppCreditCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/forecast': typeof AppForecastRoute
  '/import': typeof AppImportRoute
  '/installments': typeof AppInstallmentsRoute
  '/open-finance': typeof AppOpenFinanceRoute
  '/settings': typeof AppSettingsRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/transactions/': typeof AppTransactionsIndexRoute
  '/transactions/edit/$id': typeof AppTransactionsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/chat': typeof AppChatRoute
  '/credit-cards': typeof AppCreditCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/forecast': typeof AppForecastRoute
  '/import': typeof AppImportRoute
  '/installments': typeof AppInstallmentsRoute
  '/open-finance': typeof AppOpenFinanceRoute
  '/settings': typeof AppSettingsRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/transactions/edit/$id': typeof AppTransactionsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/credit-cards': typeof AppCreditCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/import': typeof AppImportRoute
  '/_app/installments': typeof AppInstallmentsRoute
  '/_app/open-finance': typeof AppOpenFinanceRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions/new': typeof AppTransactionsNewRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_app/transactions/edit/$id': typeof AppTransactionsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/chat'
    | '/credit-cards'
    | '/dashboard'
    | '/forecast'
    | '/import'
    | '/installments'
    | '/open-finance'
    | '/settings'
    | '/transactions/new'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/chat'
    | '/credit-cards'
    | '/dashboard'
    | '/forecast'
    | '/import'
    | '/installments'
    | '/open-finance'
    | '/settings'
    | '/transactions/new'
    | '/transactions'
    | '/transactions/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/reset-password'
    | '/_app/accounts'
    | '/_app/budgets'
    | '/_app/categories'
    | '/_app/chat'
    | '/_app/credit-cards'
    | '/_app/dashboard'
    | '/_app/forecast'
    | '/_app/import'
    | '/_app/installments'
    | '/_app/open-finance'
    | '/_app/settings'
    | '/_app/transactions/new'
    | '/_app/transactions/'
    | '/_app/transactions/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/open-finance': {
      id: '/_app/open-finance'
      path: '/open-finance'
      fullPath: '/open-finance'
      preLoaderRoute: typeof AppOpenFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/installments': {
      id: '/_app/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof AppInstallmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-cards': {
      id: '/_app/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof AppCreditCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/new': {
      id: '/_app/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AppTransactionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions/edit/$id': {
      id: '/_app/transactions/edit/$id'
      path: '/transactions/edit/$id'
      fullPath: '/transactions/edit/$id'
      preLoaderRoute: typeof AppTransactionsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppChatRoute: typeof AppChatRoute
  AppCreditCardsRoute: typeof AppCreditCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppForecastRoute: typeof AppForecastRoute
  AppImportRoute: typeof AppImportRoute
  AppInstallmentsRoute: typeof AppInstallmentsRoute
  AppOpenFinanceRoute: typeof AppOpenFinanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsNewRoute: typeof AppTransactionsNewRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
  AppTransactionsEditIdRoute: typeof AppTransactionsEditIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppChatRoute: AppChatRoute,
  AppCreditCardsRoute: AppCreditCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppForecastRoute: AppForecastRoute,
  AppImportRoute: AppImportRoute,
  AppInstallmentsRoute: AppInstallmentsRoute,
  AppOpenFinanceRoute: AppOpenFinanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsNewRoute: AppTransactionsNewRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
  AppTransactionsEditIdRoute: AppTransactionsEditIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
